version: "3.8"

services:
  backend:
    build: ./backend
    container_name: apple-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: apple-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
